### ISSUE TITLE
Make does not work out of the box

### ISSUE THREAD

**Issue by karras** [adfinis-sygroup/adsy-trainings#5]
Before being able to properly render the slides by executing `make` some manual workarounds are required:

* `build` directory has to be created
* The commons sources are copied to adsy-trainings/build/commons/adsy-trainings-common.src but this won't work. I had to move the whole content to adsy-trainings/build/commons

**Comment by eni23** [comment]
This is also resolved in the newest version version of training-builder.py. Build directory will be created and commons is not copied faulty anymore
